In [1]:
import pandas as pd
import numpy as np

### Reindexing
- create a new object with the values rearranged to align with the new index

In [2]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
# reindex - rearranges the data according to the new index
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=["a", "c", "d"],
                    columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [5]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [6]:
# columns can be reindexed with the columns keyword
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [7]:
# we can also reindex by using loc operator (preferable way)
# works only if all of the new index lables already exist in the DataFrame
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

### Dropping Entries from an Axis
- `drop` method will return a new object with the indicated value or values deleted from an axis

In [8]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [9]:
# dropping the row with index of "c"
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [10]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [11]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
            index=["Ohio", "Colorado", "Utah", "New York"],
            columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
# drop values from the row labels (axis 0)
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
# drop labels from the columns, instead use the column keyword
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### Indexing, Selection, and Filtering

In [14]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [15]:
obj["b"]

np.float64(1.0)

In [16]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [17]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [18]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [19]:
# preferred way to select index values
# because of the different treatment of integers when indexing with []
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [20]:
# example
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])

In [21]:
obj1

2    1
0    2
1    3
dtype: int64

In [22]:
obj2

a    1
b    2
c    3
dtype: int64

In [23]:
obj1[[0, 1, 2]]
# obj2[[0, 1, 2]] -> error (index does not contain integers)

0    2
1    3
2    1
dtype: int64

In [25]:
# endpoint - inclusive (works differently from normal Python slicing)
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [ ]:
# assigning values using loc method
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [27]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
            index=["Ohio", "Colorado", "Utah", "New York"],
            columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
# accessing specified column
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [31]:
data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

### Selection on DataFrame with loc and iloc
- `loc`: label-based indexing
- `iloc`: integer-based indexing

In [ ]:
# select a single row by label
data.loc["Colorado"]

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [35]:
# select multiple rows, pass a sequence of labels
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    4    5      6     7
New York   12   13     14    15

In [ ]:
# combine both row and column selection
# by separating the selections with a comma
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [ ]:
# select a single row by integer
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [37]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    4    5      6     7

In [38]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [39]:
data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    4    5
Utah        11    8    9

### Function Application and Mapping

In [41]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
            columns=list("bde"),
            index=["Utah", "Ohio", "Texas", "Oregon"])

frame

               b         d         e
Utah    0.905485 -0.596039 -0.336749
Ohio   -0.881190 -0.076260  0.636446
Texas  -1.611516 -0.109794  0.518534
Oregon  1.659409  1.152128 -1.573012

In [42]:
np.abs(frame)

               b         d         e
Utah    0.905485  0.596039  0.336749
Ohio    0.881190  0.076260  0.636446
Texas   1.611516  0.109794  0.518534
Oregon  1.659409  1.152128  1.573012

In [44]:
# computes the difference between the maximum and minimum of a Series
def f1(x):
    return x.max() - x.min()

# invoked once on each column in frame
frame.apply(f1)

b    3.270925
d    1.748168
e    2.209459
dtype: float64

In [ ]:
# invoked once per row instead - apply across the columns
frame.apply(f1, axis="columns")

Utah      1.501524
Ohio      1.517637
Texas     2.130050
Oregon    3.232421
dtype: float64

In [ ]:
def my_format(x):
    return f"{x:.2f}"

# apply an element-wise function
frame["e"].map(my_format)

Utah      -0.34
Ohio       0.64
Texas      0.52
Oregon    -1.57
Name: e, dtype: str

### Sorting and Ranking

In [48]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [ ]:
# sort object by index
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [51]:
# with DataFrame, we can sort by index on either axis
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                    index=["three", "one"],
                    columns=["d", "a", "b", "c"])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [52]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [53]:
frame.sort_index(axis="columns")

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [ ]:
# descending order
frame.sort_index(axis="columns", ascending=False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [55]:
# sort a Series by its values
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [ ]:
# missing values will be sorted to the end of the Series
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [ ]:
# missing values can be sorted to the start
obj.sort_values(na_position="first")

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

In [60]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [61]:
frame.sort_values("b")

   b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [62]:
# to sort by multiple columns, pass a list of names
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [ ]:
# rank method breaks ties by assigning each group the mean rank
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [ ]:
# ranks can also be assigned according to the order in which they're observed
# without breaking the tie
obj.rank(method="first")

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [ ]:
# rank - descending order
obj.rank(ascending=False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [66]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1], "c": [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [ ]:
# ranks over the columns
frame.rank(axis="columns")

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0